/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "FA1.v:3" *)
module fulladder(x, y, cin, A, cout);
  (* src = "FA1.v:5" *)
  wire [1:0] _0_;
  (* src = "FA1.v:5" *)
  wire [1:0] _1_;
  (* src = "FA1.v:3" *)
  output A;
  (* src = "FA1.v:3" *)
  input cin;
  (* src = "FA1.v:3" *)
  output cout;
  (* src = "FA1.v:3" *)
  input x;
  (* src = "FA1.v:3" *)
  input y;
  assign _0_ = cin + (* src = "FA1.v:5" *) y;
  assign _1_ = _0_ + (* src = "FA1.v:5" *) x;
  assign { cout, A } = _1_;
endmodule
