/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "HA1.v:10" *)
module HA1(a, b, s, Cout);
  wire _0_;
  (* src = "HA1.v:14" *)
  output Cout;
  (* src = "HA1.v:11" *)
  input a;
  (* src = "HA1.v:12" *)
  input b;
  (* src = "HA1.v:13" *)
  output s;
  AND2X2 _1_ (
    .A(a),
    .B(b),
    .Y(Cout)
  );
  NOR2X1 _2_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  NOR2X1 _3_ (
    .A(_0_),
    .B(Cout),
    .Y(s)
  );
endmodule
