/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "module2.v:1" *)
module model2(A, B, C, D, F);
  wire _0_;
  (* src = "module2.v:2" *)
  input A;
  (* src = "module2.v:2" *)
  input B;
  (* src = "module2.v:2" *)
  input C;
  (* src = "module2.v:2" *)
  input D;
  (* src = "module2.v:3" *)
  output F;
  OAI22X1 _1_ (
    .A(A),
    .B(B),
    .C(C),
    .D(D),
    .Y(_0_)
  );
  INVX1 _2_ (
    .A(_0_),
    .Y(F)
  );
endmodule
