/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "scan_ff.v:3" *)
module Scan_FF(clk, select, sd, d, q);
  (* src = "scan_ff.v:15" *)
  reg _0_;
  (* src = "scan_ff.v:13" *)
  wire _1_;
  (* src = "scan_ff.v:5" *)
  input clk;
  (* src = "scan_ff.v:8" *)
  input d;
  (* src = "scan_ff.v:10" *)
  wire f;
  (* src = "scan_ff.v:9" *)
  output q;
  reg q;
  (* src = "scan_ff.v:7" *)
  input sd;
  (* src = "scan_ff.v:6" *)
  input select;
  assign _1_ = select ? (* src = "scan_ff.v:13" *) sd : d;
  always @* begin
    _0_ = f;
  end
  always @(negedge clk) begin
      q <= _0_;
  end
  assign f = _1_;
endmodule
