/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "T.v:3" *)
module T(clk, A, B, C);
  (* src = "T.v:5" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "T.v:3" *)
  input A;
  (* src = "T.v:3" *)
  output B;
  (* src = "T.v:3" *)
  output C;
  (* src = "T.v:3" *)
  input clk;
  NOR2X1 _3_ (
    .A(B),
    .B(A),
    .Y(_1_)
  );
  AND2X2 _4_ (
    .A(B),
    .B(A),
    .Y(_2_)
  );
  NOR2X1 _5_ (
    .A(_1_),
    .B(_2_),
    .Y(_0_)
  );
  DFFNEGX1 _6_ (
    .CLK(clk),
    .D(A),
    .Q(B)
  );
  DFFNEGX1 _7_ (
    .CLK(clk),
    .D(_0_),
    .Q(C)
  );
endmodule
